# backend/blocks/user/vs_ref_channel.py
# Auto-generated by SynapChart custom block editor.
# You can edit this file directly — changes take effect on server restart.

from __future__ import annotations

from blocks.base import BlockBase, PortDefinition, ParameterDefinition
from neurodata.types import NeuroData

import numpy as np


class VsRefChannel(BlockBase):

    block_type_id = "vs_ref_channel"
    display_name  = "vsRef Channel"
    category      = "Mytest"
    description   = "Selects a single channel from a multi-channel signal.Compute the difference between this channel and the reference channel.\n"
    is_custom     = True

    inputs = [
        PortDefinition(port_id="signal", data_type="NeuroData[raw_signal]", description="Multi-channel signal (N_samples × N_channels).", required=True),
    ]
    outputs = [
        PortDefinition(port_id="channel", data_type="NeuroData[raw_signal]", description="Single-channel signal (N_samples,)."),
    ]
    parameters = [
        ParameterDefinition(name="channel_index", data_type="int", default=0, description="Zero-based index of the channel to extract."),
        ParameterDefinition(name="ref_channel_index", data_type="int", default=1, description="Zero-based index of the reference channel."),
    ]

    def run(self, inputs, parameters):
        # --- User code start ---
        import numpy as np
        from neurodata.types import NeuroData
        signal: NeuroData = inputs["signal"]
        idx    = int(parameters.get("channel_index", 0))
        refidx = int(parameters.get("ref_channel_index", 0))

        arr = signal.array
        if arr.ndim == 1:
            # Single 1-D channel — return it directly (no reference subtraction).
            channel    = arr
            refchannel = np.zeros_like(arr)
            idx        = 0
        elif arr.ndim == 2:
            n_ch   = arr.shape[1]
            idx    = min(idx,    n_ch - 1)   # clamp to valid range
            refidx = min(refidx, n_ch - 1)
            channel    = arr[:, idx]
            # Only subtract ref when there is more than one channel and the
            # reference channel is different from the signal channel.
            if n_ch > 1 and refidx != idx:
                refchannel = arr[:, refidx]
            else:
                refchannel = np.zeros_like(channel)
        else:
            raise ValueError(f"Expected 1-D or 2-D array, got shape {arr.shape}.")

        ch_name = (
            signal.channel_names[idx]
            if signal.channel_names and idx < len(signal.channel_names)
            else f"ch{idx}"
        )

        return {
            "channel": NeuroData(
                data_type="raw_signal",
                array=channel-refchannel,
                sampling_rate=signal.sampling_rate,
                timestamps=signal.timestamps,
                channel_names=[ch_name],
                metadata={**signal.metadata, "channel_index": idx},
            )
        }
        # --- User code end ---
