# backend/blocks/user/load_crcns_lfp.py
# Auto-generated by SynapChart custom block editor.
# You can edit this file directly — changes take effect on server restart.

from __future__ import annotations

from blocks.base import BlockBase, PortDefinition, ParameterDefinition
from neurodata.types import NeuroData

import numpy as np


class LoadCrcnsLfp(BlockBase):

    block_type_id = "load_crcns_lfp"
    display_name  = "Load CRCNS LFP"
    category      = "CRCNS I/O"
    description   = "Loads selected channels from a CRCNS hc-11 baseName.eeg file (int16, 1250 Hz). Connect a NeuroData[epochs] time_range to restrict loading to one epoch and avoid reading the full ~11 GB file."
    is_custom     = True
    _dependencies = []

    inputs = [
        PortDefinition(port_id="time_range", data_type="NeuroData[epochs]", description="Optional: epoch time window [t_start, t_end] from select_epoch. Overrides t_start / t_end parameters when connected.", required=False),
    ]
    outputs = [
        PortDefinition(port_id="lfp", data_type="NeuroData[lfp]", description="LFP signal (n_samples × n_channels) at 1250 Hz."),
    ]
    parameters = [
        ParameterDefinition(name="session_path", data_type="str", default="", description="Path to the session folder (same folder as the .eeg file)."),
        ParameterDefinition(name="channels", data_type="str", default="0", description="Comma-separated channel indices to load, e.g. '0,1,2' or '0-9'. Default '0' loads only the first channel."),
        ParameterDefinition(name="t_start", data_type="float", default=-1.0, description="Start time in seconds. -1 = beginning of file."),
        ParameterDefinition(name="t_end", data_type="float", default=-1.0, description="End time in seconds. -1 = end of file."),
        ParameterDefinition(name="invert_signal", data_type="bool", default=False, description="Multiply the EEG signal by −1.  Disable by default; enable only if polarity inversion is needed for a specific recording convention."),
    ]

    def run(self, inputs, parameters):
        # --- User code start ---
        # numpy, NeuroData, Path and disp() are always available; import anything else you need:
        import numpy as np
        from pathlib import Path
        from neurodata.types import NeuroData
        def _parse_channels(spec: str, n_total: int) -> list[int]:
            """Parse a channel spec like '0', '0,1,2', or '0-9' into a list."""
            spec = spec.strip()
            if not spec:
                return [0]
            result: list[int] = []
            for part in spec.split(","):
                part = part.strip()
                if "-" in part:
                    a, b = part.split("-", 1)
                    result.extend(range(int(a), int(b) + 1))
                else:
                    result.append(int(part))
            return [c for c in result if 0 <= c < n_total]

        def _read_xml(xml_path: Path) -> tuple[int, int]:
            """Return (n_channels, lfp_sampling_rate) from baseName.xml."""
            import xml.etree.ElementTree as ET
            root = ET.parse(str(xml_path)).getroot()
            n_ch = int(root.find("acquisitionSystem/nChannels").text)
            sr   = int(root.find("fieldPotentials/lfpSamplingRate").text)
            return n_ch, sr

        session_path = Path(str(parameters.get("session_path", "")).strip())
        if not session_path.exists():
            raise FileNotFoundError(f"Session folder not found: {session_path}")

        # Locate .eeg and .xml
        eeg_files = sorted(session_path.glob("*.eeg"))
        xml_files = sorted(session_path.glob("*.xml"))
        if not eeg_files:
            raise FileNotFoundError(f"No .eeg file found in {session_path}")
        if not xml_files:
            raise FileNotFoundError(f"No .xml file found in {session_path}")

        eeg_path = eeg_files[0]
        xml_path = xml_files[0]

        n_total_ch, sr = _read_xml(xml_path)

        # Determine time window
        t_start = float(parameters.get("t_start", -1.0))
        t_end   = float(parameters.get("t_end",   -1.0))

        # time_range input overrides parameters when connected
        tr = inputs.get("time_range")
        if tr is not None:
            arr = np.asarray(tr.array).flatten()
            if len(arr) >= 2:
                t_start, t_end = float(arr[0]), float(arr[1])
            elif "t_start" in tr.metadata:
                t_start = float(tr.metadata["t_start"])
                t_end   = float(tr.metadata["t_end"])

        file_size   = eeg_path.stat().st_size
        n_total_smp = file_size // (n_total_ch * 2)  # int16 = 2 bytes
        total_dur   = n_total_smp / sr

        smp_start = 0 if t_start < 0 else max(0, int(t_start * sr))
        smp_end   = n_total_smp if t_end < 0 else min(n_total_smp, int(t_end * sr) + 1)
        n_smp     = smp_end - smp_start

        channels = _parse_channels(
            str(parameters.get("channels", "0")), n_total_ch
        )

        # Read the requested slice — load full rows then index columns
        with open(str(eeg_path), "rb") as fh:
            fh.seek(smp_start * n_total_ch * 2)
            raw = np.frombuffer(fh.read(n_smp * n_total_ch * 2), dtype=np.int16)

        data_full = raw.reshape(n_smp, n_total_ch)
        data      = data_full[:, channels].astype(np.float32)

        if bool(parameters.get("invert_signal", False)):
            data = data * -1.0

        t0         = 0.0 if t_start < 0 else t_start
        timestamps = (np.arange(n_smp) / sr + t0).astype(np.float64)

        return {
            "lfp": NeuroData(
                data_type     = "lfp",
                array         = data,
                sampling_rate = float(sr),
                timestamps    = timestamps,
                channel_names = [f"ch{c}" for c in channels],
                metadata      = {
                    "n_total_channels": n_total_ch,
                    "channel_indices":  channels,
                    "t_start":          float(timestamps[0]),
                    "t_end":            float(timestamps[-1]),
                    "eeg_path":         str(eeg_path),
                },
            )
        }
        # --- User code end ---
